TS-10 - Setup Database
today-software/calendar-srv pull request #1
Opened 2023-12-10 07:43 UTC by therealchiendat

## A.C.

- [x] calendar_records table is created

- [x] event_records table is created

## Screenshots:
<img width="465" alt="image" src="https://github.com/today-software/calendar-srv/assets/44085158/009bd9e8-d7ef-4595-b28a-b48a4d20a8be">
<img width="706" alt="image" src="https://github.com/today-software/calendar-srv/assets/44085158/74e7bebb-08bf-41d7-9e6e-be9688738ae8">
<img width="706" alt="image" src="https://github.com/today-software/calendar-srv/assets/44085158/356e7dd2-0a12-47fc-8d93-36d89b9501a5">

2023-12-10 23:47 UTC, mpadillaruiz submitted a review, later dismissed
Looks good.

2023-12-11 02:35 UTC, mpadillaruiz requested changes

2023-12-11 02:35 UTC, mpadillaruiz commented on .devcontainer/docker-compose.yml
> +      MYSQL_USER: root
I believe you need to remove this line. A root user is created by default when starting the DB. Then this env variable tries to create it again with the error: [Operation CREATE USER failed for 'root'@'%']. It fails because it already exists.

I removed this line and the DB started fine.

2023-12-11 06:52 UTC, therealchiendat commented on .devcontainer/docker-compose.yml
> +      MYSQL_USER: root
Strange that I don't see any errors on my end but it makes sense to remove. 

Pushed! 🎉

2023-12-11 13:23 UTC, myhathedev commented
Approved

2023-12-11 22:19 UTC, mpadillaruiz approved these changes

2023-12-11 23:22 UTC, merged